required:
  - id
  - audit
  - projectId
  - context
  - name
  - urgency
  - importance
  - timeDivident
  - groups
properties:
  id:
    type: string
    format: uuid
  audit:
    $ref: "#/definitions/Audit"
  projectId:
    type: string
    format: uuid
  tags:
    type: array
    items:
      type: string
  context:
    type: string
    format: uuid
  name:
    type: string
  description:
    type: string
  deadline:
    type: string
    format: date-time
  urgentFrom:
    type: string
    format: date-time
  estimation:
    type: integer
    minimum: 0
    maximum: 10
  urgency:
    type: integer
    minimum: 0
    maximum: 10
  importance:
    type: integer
    minimum: 0
    maximum: 10
  timeDivident:
    type: integer
    minimum: 0
    maximum: 10
  order:
    type: integer
  groups:
    type: array
    items:
      type: string
      format: uuid
