get:
  tags:
    - task
  description: Returns a user based on a single ID, if the user does not have access to the task
  operationId: findTaskById
  produces:
    - application/json
    - application/xml
  parameters:
    - name: id
      in: path
      description: ID of task to fetch
      required: true
      type: string
      format: uuid
  responses:
    '200':
      description: task response
      schema:
        $ref: '#/definitions/TaskInfo'
    '404':
      description: not found
    default:
      description: unexpected error
      schema:
        $ref: '#/definitions/ErrorModel'
patch:
  tags:
    - task
  description: Updates a task
  operationId: editTask
  produces:
    - application/json
    - application/xml
  parameters:
    - name: id
      in: path
      description: ID of task to patch
      required: true
      type: string
      format: uuid
    - name: patchOp
      in: body
      description: PatchOperations to be performed
      required: true
      schema:
        type: array
        items:
          $ref: '#/definitions/PatchOperation'
  responses:
    '200':
      description: task response
      schema:
        $ref: '#/definitions/TaskInfo'
    '404':
      description: not found
    default:
      description: unexpected error
      schema:
        $ref: '#/definitions/ErrorModel'

delete:
  tags:
    - task
  description: deletes a single task based on the ID supplied
  operationId: deleteTask
  parameters:
    - name: id
      in: path
      description: ID of task to delete
      required: true
      type: string
      format: uuid
  responses:
    '204':
      description: task deleted
    '404':
      description: not found
    default:
      description: unexpected error
      schema:
        $ref: '#/definitions/ErrorModel'
