swagger: '2.0'
host: tasks.wit3k.pl
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
tags:
  $ref: ./tags.yaml
info:
  $ref: ./info.yaml
paths:
  $ref: ./paths.yaml
definitions:
  $ref: ./definitions.yaml
